### ISSUE TITLE
Create the discussion forum

### ISSUE THREAD

**Issue by coco98** [hasura-imad/tasks#1]
https://disqus.com/
Seed it with all the FAQs that we've had so far. Add all the 34cross folks + Gaurav's TAs + Gaurav + Rikin

**Comment by shahidhk** [comment]
At [http://discourse.imad.hasura.io/](http://discourse.imad.hasura.io/)

Needs a lot of configuration, including images. @coco98 can you put somebody on this?

**Comment by shahidhk** [comment]
Email is setup using sparkpost
