### ISSUE TITLE
Change staggered k8s object creation in restart API to just 3 independent creations

### ISSUE THREAD

**Issue by coco98** [hasura-imad/tasks#9]

**Comment by coco98** [comment]
This is important for both creation and deletion. Create and delete these objects independently. Pass an array of success and failure messages back to the client in case it is important

**Comment by shahidhk** [comment]
Unlike start event, restart api cant be independent. It has to first put the new configmap and then delete the existing pod. This cannot be independent as the delete pod could happen before configmap is updated.

Start and stop can be made independent api calls.

Then also, if we are returning the response back to client, what difference does it make compared to the current scheme?

**Comment by shahidhk** [comment]
Staggered scheme continues as order is important. But errors are now propagated completely to the client
